# Generated by Django 5.2.5 on 2025-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('session', '0002_alter_session_last_message_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('USER', 'USER'), ('AI', 'AI')], db_index=True, default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_seq',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'msg_seq'], name='message_mes_session_528597_idx'),
        ),
    ]
