# Generated by Django 5.2.5 on 2025-08-21 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('reward', '0002_reward_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemexchange',
            options={'ordering': ['-exchanged_at']},
        ),
        migrations.AddField(
            model_name='itemexchange',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemexchange',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_exchanges', to='reward.reward'),
        ),
        migrations.AlterField(
            model_name='itemexchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='itemexchange',
            unique_together={('user', 'reward')},
        ),
    ]
