# Generated by Django 5.2.5 on 2025-08-22 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='turn_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'status'], name='session_ses_user_id_1baefb_idx'),
        ),
    ]
