# Generated by Django 5.2.5 on 2025-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_last_message_at_and_more'),
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='summary',
            name='sum_seq',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['session', 'sum_seq'], name='summary_sum_session_e75cf2_idx'),
        ),
    ]
