# Generated by Django 4.2.23 on 2025-08-14 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_points', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RandomQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('random_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.randomquest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='randomquest',
            index=models.Index(fields=['user', 'is_valid'], name='quest_rando_user_id_cdb138_idx'),
        ),
        migrations.AddConstraint(
            model_name='randomquest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_valid', True)), fields=('user', 'quest'), name='uq_active_randomquest_per_user_quest'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['created_at'], name='quest_quest_created_4a5155_idx'),
        ),
        migrations.AddIndex(
            model_name='acceptedquest',
            index=models.Index(fields=['is_verified'], name='quest_accep_is_veri_3a4b95_idx'),
        ),
        migrations.AddIndex(
            model_name='acceptedquest',
            index=models.Index(fields=['created_at'], name='quest_accep_created_4cc513_idx'),
        ),
        migrations.AddConstraint(
            model_name='acceptedquest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified', False)), fields=('random_quest',), name='uq_active_accept_for_randomquest'),
        ),
    ]
