# Generated by Django 5.2.5 on 2025-08-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='image',
        ),
    ]
