# Generated by Django 5.2.5 on 2025-08-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_refreshlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshLog',
        ),
    ]
