# Generated by Django 5.2.5 on 2025-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
