# Generated by Django 5.2.5 on 2025-08-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_num', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('point', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
