# Generated by Django 5.2.5 on 2025-08-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
    ]
